### ISSUE TITLE
The decimal zeros in NumberField disappear when the focus is removed.

### ISSUE THREAD

**Issue by ttekesuke** [kmdtmyk/vue-fields#42]
![image](https://github.com/kmdtmyk/vue-fields/assets/22671408/4f0ed29f-2681-4dbc-8775-8fe16e89be81)
If I put a value in the NumberField that starts with a 0 after the decimal point (e.g. 12.003), the 0 will be hidden when blurring.
The cause is probably that 003 becomes 3 by the following parsInt.
https://github.com/kmdtmyk/vue-fields/blob/master/src/lib/NumberUtil.js#L56
Since the NumberField is made with <input type="text">, I think you are using parseInt to filter input values to numbers only.
I think it would be better to use a process other than parseInt, such as a regular expression, to filter the values.

**Comment by kmdtmyk** [comment]
Fixed in version 0.2.7
